export * from "./JoinWrapper.styled"
export * from "./JoinWrap.styled"
export * from "./JoinHeader.styled"
export * from "./JoinLogo.styled"
export * from "./JoinBody.styled"
export * from "./InputBox.styled"
export * from "./Btn.styled"
