export * from "./WriteWrapper.styled"
export * from "./AllWrapper.styled"
export * from "./TopContent.styled"
export * from "./FormContent.styled"
export * from "./Category.styled"
export * from "./PlatformImg.styled"
export * from "./PostOne.styled"
export * from "./PostWrapper.styled"